name: Go Build
on:
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build -ldflags '-extldflags "-static"' -o youtube-mp3-bot
        env:
            CGO_ENABLED: 0
      - name: Upload Go binary
        uses: actions/upload-artifact@v4
        with:
          name: youtube-mp3-bot
          path: youtube-mp3-bot